CREATE TABLE test;
ALTER TABLE test ADD id INT;
ALTER TABLE test ADD text VARCHAR(255);
INSERT INTO test (id, text) VALUES (1, 'hello1');
INSERT INTO test (id, text) VALUES (2, 'hello2');
INSERT INTO test (id, text) VALUES (3, 'hello3');
INSERT INTO test (id, text) VALUES (4, 'hello4');
INSERT INTO test (id, text) VALUES (5, 'hello5');
SELECT text FROM test;
SELECT id, text FROM test;
SELECT text, id FROM test;
ALTER TABLE test ADD description VARCHAR(255);
SELECT * FROM test;